<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="27034" started-at="2017-07-07T20:18:02Z" finished-at="2017-07-07T20:18:29Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="27034" started-at="2017-07-07T20:18:02Z" finished-at="2017-07-07T20:18:29Z">
      <class name="testing.TestCC">
        <test-method status="PASS" signature="setUpAppium()[pri:0, instance:testing.TestCC@4fe3c938]" name="setUpAppium" is-config="true" duration-ms="22350" started-at="2017-07-07T15:18:02Z" finished-at="2017-07-07T15:18:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpAppium -->
        <test-method status="FAIL" signature="mytest()[pri:0, instance:testing.TestCC@4fe3c938]" name="mytest" duration-ms="15" started-at="2017-07-07T15:18:25Z" finished-at="2017-07-07T15:18:25Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at testing.datadrive.DataDrivenUsers.getLastIndexRow(DataDrivenUsers.java:64)
	at testing.TestCC.mytest(TestCC.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mytest -->
        <test-method status="PASS" signature="CleanUpAppium()[pri:0, instance:testing.TestCC@4fe3c938]" name="CleanUpAppium" is-config="true" duration-ms="4627" started-at="2017-07-07T15:18:25Z" finished-at="2017-07-07T15:18:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CleanUpAppium -->
      </class> <!-- testing.TestCC -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
